version: '3'

services: 
    server:
        container_name: babeed-server
        restart: always
        build: ./server
        volumes: 
            - ./server:/usr/src/server
            - /usr/src/app/node_modules
        ports: 
            - '8080:8080'
        links: 
            - db
        networks: 
            - appnetwork
        depends_on: 
            - db
    db:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - ~/data/db/:/data/db
        ports:
            - '27017:27017'
        networks:
            - appnetwork

networks:
    appnetwork:
        driver: bridge
        
