version: '3'

services: 
    client:
        container_name: babeed-client
        restart: always
        build: ./client
        env_file: ./client/.env
        volumes:
            - ./client:/usr/src/client
            - /usr/src/client/node_modules
        ports:
            - '8080:8080'
        links: 
            - server
        networks:
            - appnetwork
        depends_on: 
            - server
    server:
        container_name: babeed-server
        restart: always
        build: ./server
        env_file: ./server/.env
        volumes: 
            - ./server:/usr/src/server
            - /usr/src/server/node_modules
        ports: 
            - '8081:8081'
        links: 
            - db
        networks: 
            - appnetwork
        depends_on: 
            - db
    db:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - ~/data/db:/data/db
        ports:
            - '27017:27017'
        networks:
            - appnetwork

networks:
    appnetwork:
        driver: bridge
        
